apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: retail-demo
  namespace: default
spec:
  interval: 10m
  url: https://github.com/kmikholap/explore-retail-demo.git
  ref:
    branch: master

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ai-cv-app-base
  namespace: default
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: retail-demo
  path: ./applications/ai-cv-app/base
  prune: true
  timeout: 1m


---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ai-cv-app-barcelona
  namespace: flux-system
spec:
  interval: 1m
  path: "./applications/ai-cv-app/sites/barcelona" 
  prune: true  
  sourceRef:
    kind: GitRepository
    name: retail-demo 
  dependsOn:
    - name: ai-cv-app-base