apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: bcn-patch-kustomization
  namespace: ai-cv-app
bases:
  - ../base  
  - bcn-patch-data.yaml
patches:
  - bcn-patch.yaml
  