apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: retail-demo
  namespace: default
spec:
  interval: 5m
  url: https://github.com/kmikholap/explore-retail-demo.git
  ref:
    branch: main

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ai-cv-app-barcelona
  namespace: flux-system
spec:
  interval: 1m
  path: "./applications/ai-cv-app/overlays/barcelona" 
  prune: true  
  sourceRef:
    kind: GitRepository
    name: retail-demo 
  dependsOn:
    - name: ai-cv-app-base  