apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: patch-config
  namespace: default
resources:
  - ../../base  
  - bcn-patch-data.yaml

patches:
   - target:
      group: apps
      version: v1
      kind: Deployment
      name: ai-cv-app-deployment
  path: bcn-patch.yaml