apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: patch-kustomization
  namespace: default
bases:
  - ../../base  
  - bcn-patch-data.yaml
patches:
  - path: bcn-patch.yaml
