apiVersion: apps/v1
kind: Deployment
metadata:
  name: explore-retail-demo
  namespace: explore-retail-demo
spec:
  template:
    spec:
      containers:
      - name: explore-retail-demo
        env:
        - name: DEVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: explore-retail-demo-lvs
              key: DEVICE_NAME
        - name: VIDEO_URL
          valueFrom:
            configMapKeyRef:
              name: explore-retail-demo-lvs
              key: VIDEO_URL
        
