apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: explore-retail-demo
  namespace: default
spec:
  interval: 1m
  url: https://github.com/kmikholap/explore-retail-demo.git
  ref:
    branch: master
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: explore-retail-demo-apps
  namespace: default
spec:
  interval: 1m
  url: https://github.com/kmikholap/explore-retail-demo-apps.git
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ai-cv-app-base
  namespace: default
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: explore-retail-demo-apps
  path: ./base/ai-cv-app
  prune: true
  timeout: 1m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ai-cv-app-barcelona
  namespace: default
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: explore-retail-demo-apps
  path: "./sites/barcelona
  prune: true  
  dependsOn:
    - name: ai-cv-app-base